spring.application.name=Braindribbling Games
spring.thymeleaf.cache=false

app.log.level=INFO
app.secrets.base-name=games-secrets
spring.config.import=optional:classpath:${app.secrets.base-name}.properties,optional:file:/var/www/${app.secrets.base-name}.properties
