spring.application.name=Braindribbling Games
spring.thymeleaf.cache=false

spring.datasource.url=${DB_URL:<db_url>}
spring.datasource.username=${DB_USER:<db_user>}
spring.datasource.password=${DB_PASS:<db_pass>}

app.log.level=INFO
app.external-url=${PHP_EXTERNAL_URL:<php_external_url>}
app.config.environment=${ENVIRONMENT:<environment>}
app.games-service.base-url=${API_BASE_URL:<api_base_url>}
server.servlet.context-path=${SERVER_CONTEXT_PATH:<server_context_path>}